#!/bin/sh
# inkVerb updater for Inker™, verb.ink

# This updates the Inker
## This contains many version updaters to update a Inker™ sequentially, one version at a time.
## This is run at the path: /var/local/ink/${IUPDATE_REPO}/update

# DEV NOTE: Larger versions must be at the bottom, smaller versions at the top, so "descending"

# DEV INSTRUCTIONS: Put all related files for each patch in a folder named by the version number, ie 0.806

## Sample version updater:
#UPDATE_PATCH_IVERNO=
#if [ $(echo ${UPDATE_PATCH_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then

#
## Run the update scripts for this patch
#
###### SCRIPTS GO HERE #####
#
#
############################
## Set and refresh the current version into inklists
#sed -i "s/IVERNO=.*/IVERNO=${UPDATE_PATCH_IVERNO}/g" /var/local/ink/configs/inklists/inkerverno
#. /var/local/ink/configs/inklists/inkerverno
#echo "Inker updated to v${IVERNO}"
#else
#echo "${UPDATE_PATCH_VERNO} patch not necessary..."
#fi
############################


MIN_IVERNO=0.202
IUPDATE_REPO="ink-update"

## Version Check ##
### The minimum version that can use this updater
## Include the configs
. /var/local/ink/configs/inklists/inkerverno
. /var/local/verb/configs/sitenameip
## Check minimal updateable version
if [ $(echo ${MIN_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
echo "Current Verber™ version is ${IVERNO}, minimum ${MIN_IVERNO} to use this updater.
Run updateverberlegacy for older versions."
exit 22
fi

# Update Knights & repoverlist
rm -rf /var/local/ink/knights/*
cp -rf /var/local/ink/${IUPDATE_REPO}/knights/* /var/local/ink/knights/
cp -f /var/local/ink/${IUPDATE_REPO}/repoverlist /var/local/ink/configs/inklists/

# Run version-by-version updates


UPDATE_PATCH_IVERNO=0.203
if [ $(echo ${UPDATE_PATCH_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
# Run the update scripts for this patch

##### SCRIPTS GO HERE #####
cp -rf /var/local/ink/${IUPDATE_REPO}/0.203/donjon/repoupdate /var/local/ink/donjon/

# Set and refresh the current version into inklists
sed -i "s/IVERNO=.*/IVERNO=${UPDATE_PATCH_IVERNO}/g" /var/local/ink/configs/inklists/inkerverno
. /var/local/ink/configs/inklists/inkerverno
echo "Inker updated to v${IVERNO}"
else
echo "${UPDATE_PATCH_VERNO} patch not necessary..."
fi

###########################


UPDATE_PATCH_IVERNO=0.204
if [ $(echo ${UPDATE_PATCH_IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") -gt $(echo ${IVERNO} | sed -e "s/\.//" | sed -e "s/^0*//") ] ; then
#
# Run the update scripts for this patch

##### SCRIPTS GO HERE #####
# New inkerinfo file
cp -f /var/local/ink/${IUPDATE_REPO}/0.204/inkerinfo /var/local/ink/configs/

###########################
# Set and refresh the current version into inklists
sed -i "s/IVERNO=.*/IVERNO=${UPDATE_PATCH_IVERNO}/g" /var/local/ink/configs/inklists/inkerverno
. /var/local/ink/configs/inklists/inkerverno
echo "Inker updated to v${IVERNO}"
else
echo "${UPDATE_PATCH_VERNO} patch not necessary..."
fi
###########################



# Finish
echo "Inker at v${IVERNO}"

