#!/bin/sh
# inkVerb repo donjon knight, verb.ink
set -e

# This updates the SuiteCRM repo package

# How to use:
## ./updatereposuitecrm


CVAPPNAME=suitecrm
# Include the repo versions
. /var/local/ink/configs/inklists/repoverlist
DISTVER=${suitecrm}

# Announce
echo "Updating the SuiteCRM package to v${DISTVER}..."
cd /var/local/ink/repo

# Get the package
curl -LO https://sourceforge.net/projects/suitecrm/files/SuiteCRM-${DISTVER}.zip
## Check the hash
CHECKSHA=$(sha1sum SuiteCRM-${DISTVER}.zip)
if [ "${CHECKSHA}" = "${suitecrmsha} SuiteCRM-${DISTVER}.zip" ]; then
echo "Download checks out."
else
echo "SHA check failed. The downloaded file is not what was expected. Did you set both the SuiteCRM version AND the SuiteCRM SHA for .zip?"
exit 44
fi

# Set it as the new package
rm -f ${CVAPPNAME}.legacy.zip
touch ${CVAPPNAME}.current.zip
mv ${CVAPPNAME}.current.zip ${CVAPPNAME}.legacy.zip
unzip SuiteCRM-${DISTVER}.zip
rm SuiteCRM-${DISTVER}.zip
mv SuiteCRM-${DISTVER} ${CVAPPNAME}
zip -r ${CVAPPNAME}.current.zip ${CVAPPNAME}
rm -rf ${CVAPPNAME}

# Finish
echo "Done. This repo now has SuiteCRM v${DISTVER}."

