#!/bin/sh
# inkVerb repo donjon knight, verb.ink
set -e

# This updates the Drupal repo package

# How to use:
## ./updaterepodrupal


CVAPPNAME=drupal
# Include the repo versions
. /var/local/ink/configs/inklists/repoverlist
DISTVER=${drupal}

# Announce
echo "Updating the Drupal package to v${DISTVER}..."
cd /var/local/ink/repo

# Get the package
curl -LO https://ftp.drupal.org/files/projects/drupal-${DISTVER}.tar.gz
## Check the hash
CHECKSHA=$(shasum -a 256 drupal-${DISTVER}.tar.gz)
if [ "${CHECKSHA}" = "${drupalsha} drupal-${DISTVER}.tar.gz" ]; then
echo "Download checks out."
else
echo "SHA check failed. The downloaded file is not what was expected. Did you set both the Drupal version AND the Drupal SHA for .tar.gz?"
exit 44
fi

# Set it as the new package
rm -f ${CVAPPNAME}.legacy.zip
touch ${CVAPPNAME}.current.zip
mv ${CVAPPNAME}.current.zip ${CVAPPNAME}.legacy.zip
tar -xvf drupal-${DISTVER}.tar.gz
rm drupal-${DISTVER}.tar.gz
mv drupal-${DISTVER} ${CVAPPNAME}
zip -r ${CVAPPNAME}.current.zip ${CVAPPNAME}
rm -rf ${CVAPPNAME}

# Finish
echo "Done. This repo now has Drupal v${DISTVER}."

