#!/bin/sh
#inkVerbKnight! verb.ink
set -e

# This is a dummy script that simply checks whether it is being run by a normal user as sudo

# How to use:
## ./checksudo


# Check to make sure this is run as sudo, but not run by root
## If root or sudo
if [ "$(id -u)" = "0" ]; then
## If sudo is NOT present
 if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not as root. You'll have to exit to the sudoer or re-login as the sudoer. Then...
like this:
sudo ./checksudo
"
exit 22
 fi
fi
## If sudo is NOT present
if [ -z "${SUDO_COMMAND}" ]; then
echo "Run this as a sudoer sudo, not merely as a sudoer.
like this:
sudo ./checksudo
"
exit 22
fi

# Success
echo "Yep. You are a normal sudoer sudoing.
You win a starampersand! &*&"

