#!/bin/sh
#inkVerbKnight! verb.ink
set -e

# This updates the version of a vapp package in the repo.
## The file is ink/configs/inklists/repoverlist

# How to use:
## ./repoverupdate [vapp name] [version (number-decimal only)]

# Eg:
## ./repoverupdate roundcube 2.5.9


VAPP=$1
VER=$2

sed -i "s/${VAPP}.*/${VAPP}=\"${VER}\"/g" /var/local/ink/configs/inklists/repoverlist

