#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and updates the Inker core files of a Verber™, including knights and inklists
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateinker


# Include the config
. /opt/ink/conf/inkerinfo

# Download and unpack the latest checked version from the Inkver repo
cd /opt/ink/
git clone https://github.com/inkverb/${INKUPDATEREPO}

# Run the update script
chmod +x /opt/ink/${INKUPDATEREPO}/update
/opt/ink/${INKUPDATEREPO}/update

# Remove the entire updater
rm -rf /opt/ink/${INKUPDATEREPO}

