#!/bin/sh
#inkVerbSerf! verb.ink
set -e

# This downloads and updates the Inker core files of a Verber™, including knights and inklists
## If the verbdomain mod is in effect, it will automatically run again at the end of this update
## This also runs scripts that make other changes that may affect the Verber
## This is intended for updates for versions retired from the main updater

# How to use:
## ./updateinkerlegacy


# Download and unpack the latest checked version from the Inkver repo
cd /var/local/ink/
/var/local/verb/serfs/inkget verber.update.current
unzip inker.update.current.zip
rm -f verber.update.current.zip

# Run the update script
/var/local/ink/inkerer.update.current/update

# Remove the entire updater
rm -rf /var/local/ink/inker.update.current

