#!/bin/sh
#inkVerbKnight! verb.ink
set -e

# This creates the base WordPress site to be used to create a recipe for the wpadd repo
## The namespace will be cut to 7 characters so it won't mess with the list display nor break other jobs with a name too long

# How to use:
## ./wpaddaddsite [namespace] [theme/plugin option: p, t, pt ] [ "description in quotes"]
## p = contains only plugins; t = contains only themes; pt = contains both plugins and themes

# Eg:
## ./wpaddaddsite myname pt "This is My Name, plugins:.. ; themes:..."
## ./wpaddaddsite themes t "This is Great Themes, themes:..."
## ./wpaddaddsite blgplgs pt "This is Blogg-worthy plugins, plugins:.."


WPADDNAMESPACE=$(echo $1 | cut -c1-7)
WPADDPT=$2
WPADDSITEDESCRIPT=$3

# Include the config
. /var/local/ink/donjon/wpaddsites/wpaddrepo.cnf

# Check that domain is not installed
if [ -d /var/www/html/${WPADDNAMESPACE}${WPADDNAMESUFF}.${WPADDDOMAIN} ]; then
echo "That site already exists. Doing nothing."
exit 22
fi

# Create the site
/var/local/verb/serfs/addsubdomain ${WPADDNAMESPACE}${WPADDNAMESUFF} ${WPADDDOMAIN}

# Install WordPress with inkVerb's auto-update MU-plugin
/var/local/verb/serfs/installwp ${WPADDNAMESPACE}${WPADDNAMESUFF}.${WPADDDOMAIN} wp${WPADDNAMESPACE}${WPADDNAMESUFF} wp${WPADDNAMESPACE}usr ${WPADDNAMESPACE}pass
/var/local/verb/serfs/wpautoupdate ${WPADDNAMESPACE}${WPADDNAMESUFF}.${WPADDDOMAIN}

# Add the wpadd credentials
echo "${WPADDNAMESPACE}=\"${WPADDSITEDESCRIPT}\"" >> /var/local/ink/donjon/wpaddsites/wpadd.list
## use -e to allow bash escape characters
echo "${WPADDNAMESPACE}\t${WPADDPT}\t- ${WPADDSITEDESCRIPT}" >> /var/local/ink/donjon/wpaddsites/wpadd.human.list
echo "/var/local/ink/donjon/wpaddsites/updatewpaddsite ${WPADDNAMESPACE} ${WPADDPT}" >> /var/local/ink/donjon/wpaddsites/updatewpaddrepo.sh

